version: '3.9'

services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'

  client:
    restart: on-failure
    build: ./client
    ports:
      - '3000:3000'

  server:
    restart: on-failure
    build: ./server
    ports:
      - '3001:3001'
